version: "3.9"

services:
  backed-dev:
    build:
      dockerfile: ./Development.Dockerfile
      context: backend
    volumes:
      - ./backend/src/:/app/src
    ports:
      - 3000:3000
      - 27017:27017
      - 9229:9229
      - 4000:4000