services:
  postgres:
    image: 'postgres:16'
    volumes:
      - ../tools/multiple-database:/docker-entrypoint-initdb.d
    environment:
      - 'POSTGRES_MULTIPLE_DATABASES="app_clinic_demo","app_admin", "medical_shared_data"'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - 5432:5432

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - 8025:8025
      - 1025:1025
  pgadmin:
    image: dpage/pgadmin4:8.10
    restart: "no"
    ports:
      - "5050:80"
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
      - ./docker/pgadmin/pgpass:/pgadmin4/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit -1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    entrypoint: /bin/sh -c "cp -f /pgadmin4/pgpass /var/lib/pgadmin; chmod 600 /var/lib/pgadmin/pgpass; /entrypoint.sh;"
  redis:
    image: redis:7.4.0
    restart: "no"
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
