CREATE TABLE class_mkb
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR                            NOT NULL,
    code            VARCHAR                              NOT NULL,
    parent_id       INTEGER,
    parent_code     VARCHAR DEFAULT 'NULL::character varying',
    node_count      SMALLINT    DEFAULT 0                    NOT NULL,
    additional_info TEXT,
    CONSTRAINT class_mkb_pkey PRIMARY KEY (id)
);

ALTER TABLE class_mkb
    ADD CONSTRAINT class_mkb_ibfk_1 FOREIGN KEY (parent_id) REFERENCES class_mkb (id) ON UPDATE NO ACTION ON DELETE NO ACTION;


