clinic:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: secret
    username: myuser
    url: jdbc:postgresql://localhost/app_clinic_<clinic_code>

medical:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: secret
    username: myuser
    url: jdbc:postgresql://localhost/medical_shared_data

admin:
  datasource:
    url: jdbc:postgresql://localhost/app_admin
    driverClassName: org.postgresql.Driver
    username: myuser
    password: secret

spring:
  application:
    name: "hypocrates"
  flyway:
    enabled: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
  mail:
    host: "localhost"
    username: "myuser"
    password: "admin"
    port: 1025
    properties:
      mail.smtp.auth: true
  data:
    redis:
      url: "localhost"
      port: 6379

jwt:
  secret: "AZKn*S0c]?Sj<K~"
